# The following redirect is intended for SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { CALLBACK_URL = 'https://elastic-yonath-ae9854.netlify.com/callback'}